### ISSUE TITLE
sobre número de líneas en github

### ISSUE THREAD

**Issue by AM83** [TransparenciaUGR/Proyecto-IV#24]
Saludos @JJ. Abro este issue con el fin de comentar que hay una cuestión que me preocupa. 

Antes de la anterior entrega (hito 3) creíamos  que cada práctica debería estar agrupada en una carpeta distinguible, y así se procedió durante el trabajo, moviendo los ficheros de la repo a la que se hizo fork a dicha carpeta. No obstante tras la evaluación de la P3 Vd. nos señaló nuestro error y nos aclaró que todo el proceso debía ser sobre nuestros propios ficheros y sólo en la raiz de la repo, de modo que tener carpetas para las prácticas era incorrecto y debíamos corregirlo.

Procedí a corregir de buena fé la situación  tratando de "deshacer" la división entre carpetas sin borrar nada para que no perdiésemos el trabajo de P1 y P2 reflejado en commits, y para ello moví los contenidos a una carpeta "varios" y luego traspasé los ficheros de nuestra carpeta P3 a la ruta raíz del proyecto. Dicha carpeta P3 contenía nuestro trabajo y el código fuente original del proyecto del que partíamos, es decir, el de la repo original de transparente-ugr, al que hicimos fork. 

El resultado fué que todo quedó en orden, funcionando y donde debía estar tras mover varias cosas de un sitio a otro, pero al no existir en la carpeta raíz de la repo los ficheros del proyecto original hasta ese mismo momento (estaban solo en la carpeta P3), git interpreta que yo he "añadido" no sólo todo mi trabajo, sino también un gran número extra de ficheros y de líneas que se crearon el año pasado y además cree que yo soy el autor de las mismas, y de ahí mi preocupación. Véanse los siguientes 2 commits:

https://github.com/TransparenciaUGR/Proyecto-IV/commit/f1039a9d7d5b45dacba36d12986d2447b4ea2d9e

https://github.com/TransparenciaUGR/Proyecto-IV/commit/c4ce2af9515dac6cc62c586c2c59826e345cf118

Hay muchos más commits hechos por mi (68 hasta ahora, todos pueden consultarse) y "la avalancha" de líneas se debe solo a 2 o 3. Todos esos commits reflejan la cantidad de trabajo y esfuerzo volcados hasta ahora en asuntos como scripts, colaboraciones con shippable o grunt, creación y mantenimiento de Dockerfile o creación de scripts de despliegue/eliminación por citar sólo algunas cosas, pero me preocupa que se pudiera interpretar que pretendo "engañar" o "usar líneas de otros autores" por figurar las del proyecto original como mías por los motivos que he explicado.

Creía oportuno explicarlo para ver si hay alguna solución y aprovecho para aclarar que esto ha ocurrido porque este curso es la primera vez que uso Github (amén de muchas otras herramientas) y que si hay algún modo de corregirlo o alguien me dice cómo (yo no he podido) estoy encantado de que desaparezcan todas esas líneas "de más", para dejar sólo las mías y que se vea mi número real de líneas, sin llevar a confusión.

No obstante, tal y como exige la P4 en la entrega final aclararé cuales han sido mis aportaciones  y enlazaré los commits, de modo que se vea mi trabajo "real" sin problemas.

**Comment by JJ** [comment]
OK, gracias por las aclaraciones.
